import type { Metadata } from "next";
import Providers from "./provider";
import { roboto } from "./theme";
import Header from "./components/Header";
import { ToastContainer } from 'react-toastify';

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable} suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          <div className='w-full h-full flex justify-center'>
            <div className=" w-6xl h-full ">{children}</div>
          </div>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            toastClassName="custom-toast"
            progressClassName="custom-toast-progress"
          />
        </Providers>
      </body>
    </html>
  );
}

